### ISSUE TITLE
Stats aggregator reworking to support statusD protocol

### ISSUE THREAD

**Issue by muhamadazmy** [Jumpscale/jsagent#21]
Implement statsd messages according to specs

https://github.com/etsy/statsd/blob/master/docs/metric_types.md#gauges

**Comment by despiegk** [comment]
there are golang implementations
check them to see if we can reuse something
https://github.com/jbuchbinder/statsd-go

there are more

**Comment by despiegk** [comment]
https://github.com/armon/statsite
has good explanation of messages

**Comment by despiegk** [comment]
because we need the agent now and we did not follow specs its probably better to take other approach for now
- just use messages as defined in statsite (input)
- batch on agent & send batched to AC (max every 5 minutes & max every 100 messages)
- on AC take batch & send to statsite

in other words for now we only proxy over AC using out http channels we already have

**Comment by despiegk** [comment]
see 
https://github.com/Jumpscale/jsagent/wiki/Stats
i've put the statsd specs on top of page
change rest of page please to follow my suggestion from above

**Comment by muhamadazmy** [comment]
We still can change the current implementation to work according to original specs, no need to do a work around for now. Can be done by max end of tomorrow.

**Comment by despiegk** [comment]
do the workaround first
we need statsite on central site anyhow
because needs to endup in influxdb

so having this feature is not lost

the one where we aggregate at agent can be done later

-- 
kristof de spiegeleer


On July 13, 2015 at 8:57:33 AM, Muhamad Azmy (notifications@github.com) wrote:

We still can change the current implementation to work according to original specs, no need to do a work around for now. Can be done by max end of tomorrow.

**Comment by muhamadazmy** [comment]
AC already pushes the stats to influxdb. So I don't believe we need to install statsite on the central site. And if we going to do this, then this must be removed first.

**Comment by muhamadazmy** [comment]
IMHO to implement the workaround we will need to put more effort in changing both AC and the Agent more than just fixing the current implementation of statsD to match the specs. So I am against it unless we really need to do.

**Comment by despiegk** [comment]
ok fix then


On Mon, Jul 13, 2015 at 9:25 AM, Muhamad Azmy <notifications@github.com>
wrote:

> IMHO to implement the workaround we will need to put more effort in
> changing both AC and the Agent more than just fixing the current
> implementation of statsD to match the specs. So I am against it unless we
> really need to do.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jumpscale/jsagent/issues/21#issuecomment-120836746>.
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk

**Comment by muhamadazmy** [comment]
Done, implementation is fixed, and updated the wiki.

https://github.com/Jumpscale/jsagent/wiki/Stats
